#spring.datasource.url=
#spring.datasource.username=root
#spring.datasource.password=root
#spring.datasource.platform=h2
#spring.jpa.hibernate.ddl-auto=create-drop

spring:
  profiles:
    active: test
  application:
    name: Spring Boot Security + JWT

jwt:
  secret: javainuse


---
spring:
  profiles: dev
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url:  jdbc:mysql://localhost/bootdb?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false
    driver-class-name:  org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create
      database-platform:  org.hibernate.dialect.MySQL55Dialect
      generate-ddl: true
      show-sql: true
server:
  port: 8081
---

spring:
  profiles: test
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url:  jdbc:h2:mem:bootdb
    driver-class-name:  org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create
      database-platform:  org.hibernate.dialect.MySQL55Dialect
      generate-ddl: true
      show-sql: true

server:
  port: 8080